version: "3.9"  # Specify the Compose file version
services:
  db:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: gator
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gatordev
      # postgres://gator:password@localhost:5432/gatordev
    ports:
      - "5432:5432"  # Map PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_data:
